{% set name = "jupyter-archive" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 535126a0a9fd63c65eec875cb1827011d8f178594e261d40f7d4fb4c1a934ee3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  build:
    - nodejs
  host:
    - python >=3.5
    - pip
    - jupyterlab >=2.0.0,<3
  run:
    - python >=3.5
    - jupyterlab >=2.0.0,<3
    - nodejs
test:
  requires:
    - pip
  imports:
    - jupyter_archive
  commands:
    - pip check
    - jupyter lab build
    - jupyter serverextension list 2>&1 | grep -ie "jupyter_archive.*OK"
    - jupyter labextension list 2>&1 | grep -ie "@hadim/jupyter-archive.*OK"

about:
  home: https://github.com/jupyterlab-contrib/jupyter-archive
  summary: A Jupyterlab extension to make, download and extract archive files.
  description: A Jupyterlab extension to make, download and extract archive files.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
    - fcollonval
