{% set name = "jupyter-archive" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 107167c0efd9853beca4ec6b231d14b04592125b059ba64d84c2244754df3abf

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  build:
    - nodejs >=12.0.0
  host:
    - python >=3.6
    - pip
    - jupyterlab >=3.0.0,<4
    - jupyter-packaging >=0.7.9,<0.8.0
    - setuptools >=40.8.0
    - wheel
  run:
    - python >=3.6
    - jupyterlab >=3.0.0,<4
test:
  requires:
    - pip
  imports:
    - jupyter_archive
  commands:
    - pip check
    - jupyter server extension list 2>&1 | grep -ie "jupyter_archive.*OK"
    - jupyter labextension list 2>&1 | grep -ie "@hadim/jupyter-archive.*OK"

about:
  home: https://github.com/jupyterlab-contrib/jupyter-archive
  summary: A JupyterLab extension to make, download and extract archive files.
  description: A JupyterLab extension to make, download and extract archive files.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
    - fcollonval
