{% set name = "jupyter-archive" %}
{% set version = "3.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 9bf0170e0b45ac83fc46cbf1abc60f40ced5aacf0b5a1dae465eb3bdabaf17e9

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - hatchling >=1.5.0
    - hatch-jupyter-builder >=0.5
    - hatch-nodejs-version
    - jupyterlab >=4.0.0,<5
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - jupyter_server >=1.21,<3.0.0

test:
  requires:
    - jupyterlab >=4.0.0,<5
    - pip
  imports:
    - jupyter_archive
  commands:
    - pip check
    - jupyter server extension list 2>&1 | grep -ie "jupyter_archive.*OK"
    - jupyter labextension list 2>&1 | grep -ie "@hadim/jupyter-archive.*OK"

about:
  home: https://github.com/jupyterlab-contrib/jupyter-archive
  summary: A JupyterLab extension to make, download and extract archive files.
  description: A JupyterLab extension to make, download and extract archive files.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
    - fcollonval
